package main

var header = `// Code generated by unionize.
`

var packageTemplate = `package %s
`

var importTemplate = `
import (
	"unsafe"
	%s
)
`

// [1] is the name of the union type, and [2] is the size of the underlying
// buffer, [3] is the type of the buffer (for alignment purposes).
var structTemplate = `
type %[1]s struct {
	data [%[2]d]%[3]s
}
`

// when formatting, [1] is the union type name, [2] is a string representing
// the field name, and [3] is a string representing the type name.
var fieldTemplate = `
func (u *%[1]s) %[2]s() %[3]s {
	return *(*%[3]s)(unsafe.Pointer(&u.data))
}
func (u *%[1]s) %[2]sPut(v %[3]s) {
	*(*%[3]s)(unsafe.Pointer(&u.data)) = v
}
`
